setlocal
cd /d %~dp0
del "Main.aux"
del "Main.bbl"
del "Main.brf"
del "Main.blg"
del "Main.log"
del "Main.idx"
del "Main.out"
del "Main.spl"
del "Main.nav"
del "Main.out"
del "Main.snm"
del "Main.toc"
del "Main.lof"
del "Main.nls"
del "Main.nlo"
del "Main.nlg"
del "Main.lot"
del "Main.synctex.gz"